Update deploy-to-digitalocean.yml

diff --git a/.github/workflows/deploy-to-digitalocean.yml b/.github/workflows/deploy-to-digitalocean.yml
--- a/.github/workflows/deploy-to-digitalocean.yml
+++ b/.github/workflows/deploy-to-digitalocean.yml
@@ -1,15 +1,21 @@
 name: Deploy to DigitalOcean Droplet
 
 on:
-  push:
-    branches:
-      - main
+  workflow_run:
+    workflows: ["Docker"]
+    types:
+      - completed
 
 jobs:
   deploy:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Check outcome of triggered workflow
+        if: ${{ github.event.workflow_run.conclusion != 'success' }}
+        run: |
+          echo "The triggering workflow failed. Deployment will not proceed."
+          exit 1
       - name: Checkout repository
         uses: actions/checkout@v3
 
